### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by edunston**
npm audit fix: none breaking changes only

### CODE REVIEW

**Review by Spring3 — APPROVED** [review]

**Review by jkernech — APPROVED** [review]

**Review by jkernech — APPROVED** [review]

**Review by mrister — CHANGES_REQUESTED** [review]
https://github.com/sindresorhus/ama/issues/479, remove the package-lock.json

**Review by mrister — APPROVED** [review]

**Review by ykhatal — APPROVED** [review]
Please remove `package-lock.json`, i mean add it to `.gitignore`

**Review by jkernech — APPROVED** [review]

**Comment by edunston** [comment]
The fixes weren't saved the last time for some unknown reason

**Comment by edunston** [comment]
All vulnerabilities fixed. All test passed

**Pull request merged**
